name: Validate Config

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate docker-compose
        run: docker compose config

      - name: Validate Prometheus config
        run: |
          docker run --rm \
            --entrypoint /bin/promtool \
            -v ${{ github.workspace }}/prometheus:/etc/prometheus \
            prom/prometheus \
            check config /etc/prometheus/prometheus.yml